from flask import Flask, jsonify, request
import os, time, uuid, pathlib, json
from moviepy.editor import ColorClip, TextClip, CompositeVideoClip, AudioFileClip
from gtts import gTTS
from google.cloud import storage

app = Flask(__name__)
OUT_DIR = pathlib.Path('/generated')
OUT_DIR.mkdir(parents=True, exist_ok=True)

GCS_BUCKET = os.environ.get('OUTPUT_BUCKET')  # optional

def tts_to_file(text, path, lang='en'):
    t = gTTS(text=text, lang=lang)
    t.save(str(path))

def compose_short(title, script_text, duration=10):
    width, height = 720, 1280  # portrait for Shorts
    bg = ColorClip(size=(width, height), color=(20,20,20)).set_duration(duration)
    txt = TextClip(title, fontsize=60, color='white', size=(width-40, None), method='caption').set_position(('center', 50)).set_duration(5)
    body = TextClip(script_text, fontsize=40, color='white', size=(width-40, None), method='caption').set_position(('center', 300)).set_duration(duration-2)
    out_audio_path = OUT_DIR / f"{uuid.uuid4().hex}.mp3"
    tts_to_file(script_text, out_audio_path)
    audio = AudioFileClip(str(out_audio_path))
    clip = CompositeVideoClip([bg, txt, body]).set_duration(audio.duration)
    clip = clip.set_audio(audio)
    out_path = OUT_DIR / f"{uuid.uuid4().hex}.mp4"
    clip.write_videofile(str(out_path), fps=24, codec='libx264', audio_codec='aac', threads=0, verbose=False, logger=None)
    try:
        out_audio_path.unlink()
    except Exception:
        pass
    return out_path

def upload_to_gcs(local_path, bucket_name, destination_blob_name):
    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(destination_blob_name)
    blob.upload_from_filename(str(local_path))
    return f"gs://{bucket_name}/{destination_blob_name}"

@app.route('/health')
def health():
    return jsonify({'status': 'ok'})

@app.route('/compose', methods=['POST'])
def compose():
    payload = request.json or {}
    title = payload.get('title', 'Short Title')
    script = payload.get('script', 'This is a short generated by the orchestrator.')
    duration = int(payload.get('duration', 10))
    try:
        out = compose_short(title, script, duration=duration)
        result = {'local_path': str(out)}
        if GCS_BUCKET:
            dest = f"{pathlib.Path(out).name}"
            gs_uri = upload_to_gcs(out, GCS_BUCKET, dest)
            result['gcs'] = gs_uri
        return jsonify({'status': 'done', 'result': result})
    except Exception as e:
        return jsonify({'status': 'error', 'error': str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8080))
    app.run(host='0.0.0.0', port=port)
